### ISSUE TITLE
MIT license link is not working

### ISSUE THREAD

**Issue by ygz213** [ygz213/Real-file.extnsn#8]
## Versions

`Real-file.extnsn`: v3.5 (As far as I see code, since v3.3)

`Python`: 3.9.6

### Is the bug a crash?

No

### Error log

- **English:**
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "python_path\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "app_path\Real-file.extnsn\app\main.py", line 86, in <lambda>
    MIT_link.bind("<Button-1>", lambda e: ont('https://github.com/h2non/filetype.py/blob/master/LICENSE'))
NameError: name 'ont' is not defined
```
- **Turkish:**
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "python_path\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "app_path\Real-file.extnsn\app\main_turkish.py", line 86, in <lambda>
    MIT_linki.bind("<Button-1>", lambda e: ont('https://github.com/h2non/filetype.py/blob/master/LICENSE'))
NameError: name 'ont' is not defined
```

### Steps to occur the bug

**1.** Run program
**2.** Try to go to MIT License link

**Comment by ygz213** [comment]
This issue template has been deleted because people must can use Real-file.extnsn **without** terminal. Same issue with the new issue template:

## Versions

`Real-file.extnsn`: v3.5 (As far as I see code, since v3.3)

`Python`: 3.9.6

### Is the bug a crash?

No

### Describe the bug

MIT license link is not opening filetype's license tab.

### Steps to occur the bug

**1.** Run program
**2.** Try to go to MIT License link

**Comment by ygz213** [comment]
Fixed in [R-F.E v4](https://github.com/ygz213/Real-file.extnsn/releases/tag/v4).
